name: nyc-airbnb-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - jupyter
  - matplotlib
  - numpy
  - plotly
  - pyarrow
  - seaborn
prefix: /home/prof-adept/anaconda3/envs/nyc-airbnb-env
